# Generated by Django 3.2.6 on 2021-08-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
